name: SonarQube-Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    timeout-minutes: 15     
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       

      - name: Set up Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: 'npm'

      - name: Install Java (para el scanner de SonarQube)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  

      - name: Start MongoDB 8.0
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '8.0'

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage info
        run: npm run coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: '.'